#!/bin/bash


RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' 


if command -v ip > /dev/null; then

    ip_address=$(ip -4 addr show scope global | grep inet | awk '{print $2}' | cut -d/ -f1)
else

    ip_address=$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}')
fi


network=$(echo $ip_address | awk -F. '{print $1"."$2"."$3".0/24"}')


echo -e "${CYAN}Сканирование сети $network...${NC}"
ip_list=$(sudo netdiscover -r $network -P | grep " 1 " | awk '{print $1}')


for ip in $ip_list; do
    echo -e "${YELLOW}Проверка IP: $ip на наличие открытого порта SSH...${NC}"

    nmap_output=$(nmap -Pn -p 22 $ip | grep "22/tcp open")
    if [[ -n $nmap_output ]]; then
        echo -e "${GREEN}---------------------------------${NC}"
        echo -e "${GREEN}Найден открытый порт SSH на IP: $ip${NC}"
        detailed_info=$(nmap -sV -O $ip)
        echo -e "${BLUE}${detailed_info}${NC}"
        echo -e "${GREEN}---------------------------------${NC}"
    else
        echo -e "${RED}Порт SSH закрыт на IP: $ip${NC}"
    fi
done
 
